#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-DomainKeys
version:      0.80
version_from: lib/Mail/DomainKeys.pm
installdirs:  site
requires:
    Test::More:                    0
    Net::DNS:                      0.34
    MIME::Base64:                  0
    Mail::Address:                 0
    Crypt::OpenSSL::RSA:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.11
